CREATE DATABASE newark_it;
USE newark_it;

CREATE TABLE CUSTOMER (
    CID INT AUTO_INCREMENT NOT NULL,
    FName VARCHAR(25) NOT NULL,
    LName VARCHAR(25) NOT NULL,
    EMail VARCHAR(255) NOT NULL UNIQUE,
    Address VARCHAR(255) NOT NULL,
    Phone VARCHAR(25) NOT NULL,
    CPassword VARCHAR(255) NOT NULL DEFAULT '',
    Status ENUM('regular', 'silver', 'gold', 'platinum') DEFAULT 'regular',
    PRIMARY KEY (CID)
);

CREATE TABLE SILVER_AND_ABOVE (
    CID INT NOT NULL,
    CreditLine DECIMAL(10, 2) NOT NULL,
    PRIMARY KEY (CID),
    FOREIGN KEY (CID) REFERENCES CUSTOMER(CID) ON DELETE CASCADE
);

CREATE TABLE SHIPPING_ADDRESS (
    CID INT NOT NULL,
    SAName VARCHAR(50),
    RecipientName VARCHAR(50) NOT NULL,
    Street VARCHAR(100) NOT NULL,
    SNumber VARCHAR(10) NOT NULL,
    City VARCHAR(50) NOT NULL,
    Zip VARCHAR(9) NOT NULL,
    State VARCHAR(15) NOT NULL,
    Country VARCHAR(50) NOT NULL,
    PRIMARY KEY (CID, SAName),
    FOREIGN KEY (CID) REFERENCES CUSTOMER(CID) ON DELETE CASCADE
);

CREATE TABLE CREDIT_CARD (
    CCNumber VARCHAR(20) NOT NULL,
    SecNumber VARCHAR(4) NOT NULL,
    OwnerName VARCHAR(100) NOT NULL,
    CCType VARCHAR(25) NOT NULL,
    BilAddress VARCHAR(255) NOT NULL,
    ExpDate DATE NOT NULL,
    StoredCardCID INT,
    PRIMARY KEY (CCNumber),
    FOREIGN KEY (StoredCardCID) REFERENCES CUSTOMER(CID) ON DELETE SET NULL
);

CREATE TABLE PRODUCT (
    PID INT AUTO_INCREMENT NOT NULL,
    PType VARCHAR(50) NOT NULL,
    PName VARCHAR(100) NOT NULL,
    PPrice DECIMAL(10, 2) NOT NULL,
    PDescription TEXT,
    PQuantity INT NOT NULL DEFAULT 0,
    PRIMARY KEY (PID)
);

CREATE TABLE COMPUTER (
    PID INT NOT NULL,
    CPUType VARCHAR(50) NOT NULL,
    PRIMARY KEY (PID),
    FOREIGN KEY (PID) REFERENCES PRODUCT(PID) ON DELETE CASCADE
);

CREATE TABLE PRINTER (
    PID INT NOT NULL,
    PrinterType VARCHAR(50) NOT NULL,
    Resolution VARCHAR(50) NOT NULL,
    PRIMARY KEY (PID),
    FOREIGN KEY (PID) REFERENCES PRODUCT(PID) ON DELETE CASCADE
);

CREATE TABLE LAPTOP (
    PID INT NOT NULL,
    BType VARCHAR(50) NOT NULL,
    Weight DECIMAL(5, 2) NOT NULL,
    PRIMARY KEY (PID),
    FOREIGN KEY (PID) REFERENCES PRODUCT(PID) ON DELETE CASCADE
);

CREATE TABLE OFFER_PRODUCT (
    PID INT NOT NULL,
    OfferPrice DECIMAL(10, 2) NOT NULL,
    PRIMARY KEY (PID),
    FOREIGN KEY (PID) REFERENCES PRODUCT(PID) ON DELETE CASCADE
);

CREATE TABLE BASKET (
    BID INT AUTO_INCREMENT NOT NULL,
    CID INT NOT NULL,
    PRIMARY KEY (BID),
    FOREIGN KEY (CID) REFERENCES CUSTOMER(CID) ON DELETE CASCADE
);

CREATE TABLE APPEARS_IN (
    BID INT NOT NULL,
    PID INT NOT NULL,
    Quantity INT NOT NULL,
    PriceSold DECIMAL(10, 2) NOT NULL,
    PRIMARY KEY (BID, PID),
    FOREIGN KEY (BID) REFERENCES BASKET(BID) ON DELETE CASCADE,
    FOREIGN KEY (PID) REFERENCES PRODUCT(PID) ON DELETE CASCADE
);

CREATE TABLE TRANSACTION (
    BID INT NOT NULL,
    CCNumber VARCHAR(20) NOT NULL,
    CID INT NOT NULL,
    SAName VARCHAR(50) NOT NULL,
    TDate DATETIME DEFAULT CURRENT_TIMESTAMP,
    TTag ENUM('delivered', 'not-delivered') DEFAULT 'delivered',
    PRIMARY KEY (BID),
    FOREIGN KEY (BID) REFERENCES BASKET(BID) ON DELETE CASCADE,
    FOREIGN KEY (CCNumber) REFERENCES CREDIT_CARD(CCNumber) ON DELETE RESTRICT,
    FOREIGN KEY (CID, SAName) REFERENCES SHIPPING_ADDRESS(CID, SAName) ON DELETE RESTRICT
);
